## SPAFIT - Small Python Application Freezer/Installer Test ##
| Tool | Win | Mac | Issue |
|------|-----|-----|-------|
| briefcase | :no_entry: Not Supported | :x: FAIL | Oct 30 12:38:18 jamesmacbookpro com.apple.xpc.launchd[1] (co.abel.main.368672[35315]): Service exited with abnormal code: 1<br>Traceback (most recent call last):<br>File "/Users/james/projects/spafit/test_briefcase_mac/macOS/main.app/Contents/Resources/python/lib/python3.5/runpy.py", line 184, in _run_module_as_main<br>"__main__", mod_spec)<br>File "/Users/james/projects/spafit/test_briefcase_mac/macOS/main.app/Contents/Resources/python/lib/python3.5/runpy.py", line 85, in _run_code<br>exec(code, run_globals)<br>File "/Users/james/projects/spafit/test_briefcase_mac/macOS/main.app/Contents/Resources/app/main/app.py", line 6, in <module><br>import cryptography.fernet<br>File "/Users/james/projects/spafit/test_briefcase_mac/macOS/main.app/Contents/Resources/app_packages/cryptography/fernet.py", line 17, in <module><br>from cryptography.hazmat.primitives import hashes, padding<br>File "/Users/james/projects/spafit/test_briefcase_mac/macOS/main.app/Contents/Resources/app_packages/cryptography/hazmat/primitives/padding.py", line 13, in <module><br>from cryptography.hazmat.bindings._padding import lib<br>ImportError: No module named '_cffi_backend' |
| cx_freeze | :x: FAIL | :x: FAIL | <br># *** Python 3.5 ***<br><br>Win32GUI.c<br>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:c:\users\james\projects\spafit\test_cx_freeze\venv\libs /LIBPATH:c:\Users\jame<br>s\AppData\Local\Programs\Python\Python35\libs /LIBPATH:c:\Users\james\AppData\Local\Programs\Python\Python35 /LIBPATH:c:\users\james\projects\spafit\test_cx_freeze\venv\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Micr<br>osoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10586.0\ucrt\x64" "/LIBPATH:C:\Program F<br>iles (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10586.0\um\x64" user32.lib build\temp.win-amd64-3.5\Release\source/bases/Win32GUI.obj /OUT:build\lib.win-amd64-<br>3.5\cx_Freeze\bases\Win32GUI.exe /MANIFEST<br>Generating code<br>Finished generating code<br>running build_scripts<br>creating build\scripts-3.5<br>copying and adjusting cxfreeze -> build\scripts-3.5<br>copying and adjusting cxfreeze-quickstart -> build\scripts-3.5<br>error: file 'C:\Users\james\AppData\Local\Temp\pip-build-v084ipn9\cx-freeze\cxfreeze-postinstall' does not exist<br><br>----------------------------------------<br>Command "c:\users\james\projects\spafit\test_cx_freeze\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\james\\AppData\\Local\\Temp\\pip-build-v084ipn9\\cx-freeze\\setup.py';exec(compile(ge<br>tattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\james\AppData\Local\Temp\pip-cmdndupo-record\install-record.txt --single-version-externally-managed --co<br>mpile --install-headers c:\users\james\projects\spafit\test_cx_freeze\venv\include\site\python3.5\cx-freeze" failed with error code 1 in C:\Users\james\AppData\Local\Temp\pip-build-v084ipn9\cx-freeze\<br><br><br># *** Python 3.4 ***<br><br>c:\Users\james\projects\spafit\test_cx_freeze>venv\Scripts\pip3.exe install -U -r requirements.txt<br>Collecting PyQt5 (from -r requirements.txt (line 1))<br>Could not find a version that satisfies the requirement PyQt5 (from -r requirements.txt (line 1)) (from versions: )<br>No matching distribution found for PyQt5 (from -r requirements.txt (line 1))<br><br>c:\Users\james\projects\spafit\test_cx_freeze><br>error: [Errno 2] No such file or directory: '/Users/james/projects/spafit/test_cx_freeze_mac/venv/lib/QtCore.framework/Versions/5/QtCore' |
| osnap | :white_check_mark: PASS | :white_check_mark: PASS |  |
| py2app | :no_entry: Not Supported | :x: FAIL | Oct 29 16:16:40 jamesmacbookpro main[12555]: main Error<br>Oct 29 16:16:40 jamesmacbookpro main[12555]: 2016-10-29 16:16:40.767 main[12555:171326] main Error<br>Oct 29 16:16:42 jamesmacbookpro main[12555]: Traceback (most recent call last):<br>Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "/Users/james/projects/spafit/test_py2app/dist/main.app/Contents/Resources/__boot__.py", line 351, in <module><br>Oct 29 16:16:42 jamesmacbookpro main[12555]:     _run()<br>Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "/Users/james/projects/spafit/test_py2app/dist/main.app/Contents/Resources/__boot__.py", line 336, in _run<br>Oct 29 16:16:42 jamesmacbookpro main[12555]:     exec(compile(source, path, 'exec'), globals(), globals())<br>Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "/Users/james/projects/spafit/test_py2app/dist/main.app/Contents/Resources/main.py", line 4, in <module><br>Oct 29 16:16:42 jamesmacbookpro main[12555]:     from PyQt5.QtWidgets import QApplication, QLabel<br>Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "PyQt5/QtWidgets.pyc", line 14, in <module><br>Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "PyQt5/QtWidgets.pyc", line 10, in __load<br>Oct 29 16:16:42 jamesmacbookpro main[12555]:   File "imp.pyc", line 342, in load_dynamic<br>Oct 29 16:16:42 jamesmacbookpro main[12555]: ImportError: dlopen(/Users/james/projects/spafit/test_py2app/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so, 2): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets<br>Oct 29 16:16:42 jamesmacbookpro main[12555]:   Referenced from: /Users/james/projects/spafit/test_py2app/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so<br>Oct 29 16:16:42 jamesmacbookpro main[12555]:   Reason: image not found<br>Oct 30 12:48:33 jamesmacbookpro main[46379]: main Error<br>Oct 30 12:48:33 jamesmacbookpro main[46379]: 2016-10-30 12:48:33.404 main[46379:614753] main Error<br>Oct 30 12:50:51 jamesmacbookpro main[46379]: Traceback (most recent call last):<br>Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/__boot__.py", line 351, in <module><br>Oct 30 12:50:51 jamesmacbookpro main[46379]:     _run()<br>Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/__boot__.py", line 336, in _run<br>Oct 30 12:50:51 jamesmacbookpro main[46379]:     exec(compile(source, path, 'exec'), globals(), globals())<br>Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/main.py", line 4, in <module><br>Oct 30 12:50:51 jamesmacbookpro main[46379]:     from PyQt5.QtWidgets import QApplication, QLabel<br>Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "PyQt5/QtWidgets.pyc", line 14, in <module><br>Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "PyQt5/QtWidgets.pyc", line 10, in __load<br>Oct 30 12:50:51 jamesmacbookpro main[46379]:   File "imp.pyc", line 342, in load_dynamic<br>Oct 30 12:50:51 jamesmacbookpro main[46379]: ImportError: dlopen(/Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so, 2): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets<br>Oct 30 12:50:51 jamesmacbookpro main[46379]:   Referenced from: /Users/james/projects/spafit/test_py2app_mac/dist/main.app/Contents/Resources/lib/python3.5/lib-dynload/PyQt5/QtWidgets.so<br>Oct 30 12:50:51 jamesmacbookpro main[46379]:   Reason: image not found |
| py2exe | :x: FAIL | :no_entry: Not Supported | running py2exe<br><br>4 missing Modules<br>------------------<br>? pkg_resources.extern.appdirs        imported from pkg_resources<br>? pkg_resources.extern.packaging      imported from pkg_resources<br>? pkg_resources.extern.six            imported from pkg_resources<br>? readline                            imported from cmd, code, pdb<br>Building 'dist\main.exe'.<br>error: [Errno 2] No such file or directory: 'c:\\Users\\james\\projects\\spafit\\test_py2exe\\venv\\lib\\site-packages\\py2exe\\run_w-py3.5-win-amd64.exe'<br>Traceback (most recent call last):<br>File "main.py", line 4, in <module><br>File "c:\python34\lib\site-packages\zipextimporter.py", line 109, in load_module<br>self.get_data)<br>ImportError: No module named 'sip' |
| pyinstaller | :x: FAIL | :x: FAIL | Traceback (most recent call last):<br>File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 46, in <module><br>File "c:\users\james\projects\spafit\test_pyinstaller\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 573, in load_module<br>module = loader.load_module(fullname)<br>ImportError: DLL load failed: The specified procedure could not be found.<br>PyInstaller Bootloader 3.x<br>Failed to execute script pyi_rth_qt5plugins<br><br>2547 INFO: Processing pre-safe import module hook   win32com<br>Traceback (most recent call last):<br>File "<string>", line 2, in <module><br>ImportError: No module named 'win32com'<br>2590 INFO: Processing pre-safe import module hook   win32com<br>Traceback (most recent call last):<br>File "<string>", line 2, in <module><br>ImportError: No module named 'win32com'<br>2630 INFO: Processing pre-safe import module hook   win32com<br>Traceback (most recent call last):<br>File "<string>", line 2, in <module><br>ImportError: No module named 'win32com'<br>2670 INFO: Processing pre-safe import module hook   win32com<br>Traceback (most recent call last):<br>File "<string>", line 2, in <module><br>ImportError: No module named 'win32com'<br><br>3507 INFO: Looking for dynamic libraries<br>3509 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)<br>3509 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)<br>...<br>3657 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/james/projects/spafit/test_pyinstaller_mac/venv/lib/python3.5/site-packages/PyQt5/QtWidgets.so)<br>3661 INFO: Looking for eggs<br>3661 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.5/Python<br>3677 INFO: Warnings written to /Users/james/projects/spafit/test_pyinstaller_mac/build/main/warnmain.txt<br> |
| pynsist | :white_check_mark: PASS | :no_entry: Not Supported |  |

Notes
- Generally tried to use Python 3.5.  If a tool failed with 3.5 I tried 3.4.  However, no tool that failed on 3.5 then passed on 3.4.
    
